"use strict";
let placetovisit = ["Hongkong", "America", "Pakistan", "Brazil", "Iran"];
//console.log(placetovisit);
//console.log(placetovisit.sort());
//console.log(placetovisit);
//console.log(placetovisit.sort().reverse());
//console.log(placetovisit);
//console.log(placetovisit.reverse());
//console.log(placetovisit.reverse());
let sortedArray = ["Hongkong", "America", "Pakistan", "Brazil", "Iran"];
sortedArray.sort();
console.log(sortedArray);
sortedArray.reverse();
console.log(sortedArray);
